export { TARGETS, LOOKBACK_WEEKS } from "./config";
export type { Target } from "./config";
export { isTradingDay, lastTradingDayOfWeek } from "./trading-day";
export { basisClose, cumulativeReturn } from "./momentum";
export { decide, resolveAction, ACTION_LABELS } from "./decide";
export type { Candidate, Decision, RotationAction } from "./decide";
export { runRotation } from "./run-rotation";
export type { RotationResult } from "./run-rotation";
export { findNextRotation, shanghaiDateStr, rotationInstant } from "./scheduler";
export { alignWeeks, backtest } from "./backtest";
export type { AlignedWeeks, BacktestOptions, BacktestResult, Trade } from "./backtest";
export { runBacktest } from "./run-backtest";
export { sendServerChan } from "./notify";
