name: E2E Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'playwright.config.ts'

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
        exclude:
          # WebKit only works on macOS and Linux
          - os: windows-latest
            browser: webkit
            
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
      
    - name: Setup Rust (for Tauri)
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install Tauri dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        
    - name: Build application
      run: npm run build
      
    - name: Run E2E tests
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-report-${{ matrix.os }}-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
          
    - name: Upload screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots-${{ matrix.os }}-${{ matrix.browser }}
        path: test-results/
        
  visual-regression:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Build application
      run: npm run build
      
    - name: Run visual regression tests
      run: npm run test:visual
      
    - name: Upload visual diff reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: visual-regression-report
        path: |
          visual-regression-report/
          test-results/
          
  performance-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Build application
      run: npm run build
      
    - name: Run performance tests
      run: npm run performance:monitor
      
    - name: Upload performance reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: performance-reports
        path: |
          performance-reports/
          lighthouse-reports/